# Utilise Python 3.11 slim
FROM python:3.11-slim

# Définir le répertoire de travail dans le container
WORKDIR /app

# Copier le code Python
COPY . .

# Installer les dépendances
RUN pip install flask

# Exposer le port 8080
EXPOSE 8080

# Lancer l'application
CMD ["python", "app.py"]
