# Étape 1 : image Python
FROM python:3.11-slim

WORKDIR /app

# Copier les fichiers
COPY . .

# Installer les dépendances
RUN pip install flask

# Exposer le port
EXPOSE 8080

# Lancer l'application
CMD ["python", "app.py"]
